### ISSUE TITLE
Button On hover color and effects

### ISSUE THREAD

**Issue by vdanelia** [tomaggio83/scroll-to-top#1]
Hello How I can add on hover color and some effects like fade effect..
Also font awesome icon not displayed correctly...

**Comment by tomsime** [comment]
Sorry, I inserted fontawesome just as an example. You're right, I had to specify that.

If you want it you have to include following the [instruction from website][1]

For hover effect, and any other effect, you can use css. 

Thank you for your questions, I love others opinions to improve my work :)

[1]: http://fontawesome.io/get-started/

**Comment by vdanelia** [comment]
Hello, I inserted it from font awesome, now i have another questions...
How to add some options (for the scrollup button) such as:
Fontweight:
fontsize:
bordersize:
bordercolor: etc..
on hover....

If you explain me I can do it myself... I found the options in "js" file, but there are not many..

Thank you in advanced!

**Comment by vdanelia** [comment]
Yes, From CSS it's possible, I thought that would add some functions in "js" file...
Ok thank you, I liked your script, really very smart and easy...
