### ISSUE TITLE
No release tag, broken versioning

### ISSUE THREAD

**Issue by mirabilos** [tomaggio83/scroll-to-top#3]
Your .js file says version 1.0 despite being changed all the time; there are no proper tagged releases, nor is the version number increased on each change.

**Comment by tomsime** [comment]
You right, I update it right now.
I'm new here and I have to just get used to it. Thank you for your suggestion.

**Comment by mirabilos** [comment]
OK, thanks… now if you would please tag 6441c6bd329078c90e62813a0ddaa5ae3485ca6c as v1.0.4 and remember to do so for all future changes? ;-)

**Comment by tomsime** [comment]
I did it ;-)
Thanks for helping me.
